import {ReactNode,useState} from "react";
import {Link,useLocation,useNavigate} from "react-router-dom";
import {Bell,BookOpen,CalendarDays,ChevronDown,ChevronLeft,ChevronRight,CircleHelp,ClipboardList,Contact,FileText,GraduationCap,LayoutDashboard,LogOut,Menu,MessageSquare,Search,Settings,ShieldCheck,Star,Users,X,Plus,PlayCircle,BarChart3,CheckCircle2} from "lucide-react";
import {useAuth} from "./auth";

export const cn=(...x:(string|false|undefined)[])=>x.filter(Boolean).join(" ");
export function Logo(){return <Link to="/" className="flex items-center gap-2 font-bold text-brand text-lg"><span className="grid place-items-center w-8 h-8 rounded-xl bg-brand text-white">♥</span>Heartify</Link>}
const studentNav=[["Dashboard","/student/dashboard",LayoutDashboard],["My Courses","/student/my-courses",BookOpen],["Lessons","/student/lessons",PlayCircle],["Assignments","/student/assignments",ClipboardList],["Quizzes","/student/quizzes",FileText],["Exams","/student/exams",GraduationCap],["Calendar","/student/calendar",CalendarDays],["Progress","/student/progress",BarChart3],["Certificates","/student/certificates",ShieldCheck],["Messages","/student/messages",MessageSquare],["Notifications","/student/notifications",Bell],["Profile","/student/profile",Users],["Settings","/student/settings",Settings]];
const instructorNav=[["Dashboard","/instructor/dashboard",LayoutDashboard],["Courses","/instructor/courses",BookOpen],["Create Course","/instructor/create-course",Plus],["Lessons","/instructor/lessons",PlayCircle],["Assignments","/instructor/assignments",ClipboardList],["Quizzes","/instructor/quizzes",FileText],["Exams","/instructor/exams",GraduationCap],["Students","/instructor/students",Users],["Gradebook","/instructor/gradebook",BarChart3],["Attendance","/instructor/attendance",CheckCircle2],["Live Classes","/instructor/live-classes",CalendarDays],["Messages","/instructor/messages",MessageSquare],["Settings","/instructor/settings",Settings]];
const adminNav=[["Dashboard","/admin/dashboard",LayoutDashboard],["Users","/admin/users",Users],["Instructors","/admin/instructors",GraduationCap],["Courses","/admin/courses",BookOpen],["Categories","/admin/categories",LayoutDashboard],["Enrollments","/admin/enrollments",ClipboardList],["Assignments","/admin/assignments",ClipboardList],["Quizzes","/admin/quizzes",FileText],["Exams","/admin/exams",GraduationCap],["Certificates","/admin/certificates",ShieldCheck],["Reviews","/admin/reviews",Star],["Reports","/admin/reports",BarChart3],["Notifications","/admin/notifications",Bell],["Support","/admin/support",CircleHelp],["Settings","/admin/settings",Settings]];
export function Sidebar({role}:{role:"student"|"instructor"|"admin"}){
 const [open,setOpen]=useState(true);const nav=role==="student"?studentNav:role==="instructor"?instructorNav:adminNav;const loc=useLocation();
 return <aside className={cn("fixed left-0 top-0 bottom-0 z-40 bg-white border-r border-slate-100 transition-all",open?"w-56":"w-16")}>
  <div className="h-16 px-4 flex items-center justify-between border-b border-slate-100"><Logo/>{open&&<button onClick={()=>setOpen(false)} className="text-slate-400"><ChevronLeft size={17}/></button>}</div>
  {!open&&<button onClick={()=>setOpen(true)} className="m-4 text-slate-400"><Menu size={18}/></button>}
  <nav className="p-3 space-y-1 overflow-y-auto h-[calc(100vh-64px)]">
   {nav.map(([label,to,Icon]:any)=><Link key={to} title={label} to={to} className={cn("flex items-center gap-3 rounded-xl px-3 py-2.5 text-[13px]",loc.pathname===to?"bg-[#F0ECFF] text-brand font-semibold":"text-slate-500 hover:bg-slate-50")}>{<Icon size={17}/>} {open&&label}</Link>)}
  </nav>
 </aside>
}
export function Topbar({title,subtitle}:{title:string;subtitle?:string}){const {user,logout}=useAuth();const nav=useNavigate();return <header className="h-16 bg-white border-b border-slate-100 flex items-center justify-between px-6 sticky top-0 z-30"><div><h1 className="font-semibold text-lg">{title}</h1>{subtitle&&<p className="text-xs text-slate-400">{subtitle}</p>}</div><div className="flex items-center gap-3"><div className="hidden md:flex items-center bg-slate-50 rounded-xl px-3 py-2 w-48"><Search size={15} className="text-slate-400"/><input placeholder="Search..." className="bg-transparent outline-none text-xs ml-2 w-full"/></div><button className="p-2 rounded-xl hover:bg-slate-50"><Bell size={18}/></button><button onClick={()=>nav(`/${user?.role||"student"}/profile`)} className="flex items-center gap-2"><img src="https://i.pravatar.cc/64?img=12" className="w-8 h-8 rounded-full" /><span className="hidden sm:block text-sm">{user?.first_name||"Alex"} {user?.last_name||"Morgan"}</span><ChevronDown size={14}/></button><button onClick={logout} title="Logout" className="text-slate-400"><LogOut size={17}/></button></div></header>}
export function AppShell({role,children,title,subtitle}:{role:"student"|"instructor"|"admin";children:ReactNode;title:string;subtitle?:string}){return <div className="min-h-screen bg-[#F8F7FC]"><Sidebar role={role}/><main className="ml-56"><Topbar title={title} subtitle={subtitle}/><div className="p-6 max-w-[1440px] mx-auto">{children}</div></main></div>}
export function Card({children,className=""}:{children:ReactNode;className?:string}){return <div className={cn("bg-white rounded-2xl border border-slate-100 shadow-soft",className)}>{children}</div>}
export function Stat({label,value,change,icon:Icon}:{label:string;value:string;change?:string;icon?:any}){return <Card className="p-4"><div className="flex justify-between"><div><p className="text-xs text-slate-400">{label}</p><p className="text-2xl font-bold mt-1">{value}</p>{change&&<p className="text-[11px] text-brand mt-1">{change}</p>}</div>{Icon&&<span className="w-9 h-9 rounded-xl bg-[#F0ECFF] text-brand grid place-items-center"><Icon size={18}/></span>}</div></Card>}
export function Table({headers,rows}:{headers:string[];rows:(string|number|boolean|undefined)[][]}){return <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-[#F3F0FF] text-[11px] text-slate-500"><tr>{headers.map(h=><th key={h} className="px-5 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((r,i)=><tr key={i} className="text-xs hover:bg-slate-50">{r.map((c,j)=><td key={j} className="px-5 py-4 text-slate-600">{j===r.length-1&&typeof c==="string"&&["Active","Pending","Submitted","Graded","Open","Read","Resolved","Unread"].includes(c)?<span className="px-2 py-1 rounded-full bg-[#F0ECFF] text-brand">{c}</span>:c}</td>)}</tr>)}</tbody></table></div></Card>}
export function PageTitle({title,desc,button}:{title:string;desc?:string;button?:string}){return <div className="flex items-end justify-between mb-5"><div><h2 className="text-xl font-bold">{title}</h2>{desc&&<p className="text-xs text-slate-400 mt-1">{desc}</p>}</div>{button&&<button className="bg-brand text-white rounded-xl px-4 py-2 text-xs font-semibold flex items-center gap-2"><Plus size={15}/>{button}</button>}</div>}
export function LineChart(){return <div className="h-52 relative"><svg viewBox="0 0 700 210" className="w-full h-full"><path d="M0 175 L80 140 L160 155 L240 112 L320 132 L400 75 L480 98 L560 48 L700 65" fill="none" stroke="#6D4AFF" strokeWidth="3"/><path d="M0 175 L80 140 L160 155 L240 112 L320 132 L400 75 L480 98 L560 48 L700 65 L700 210 L0 210Z" fill="#6D4AFF" opacity=".06"/></svg><div className="absolute bottom-0 left-0 right-0 flex justify-between text-[10px] text-slate-400"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div>}
