import {useEffect,useState,type ReactNode} from "react";
import {Link,useNavigate,useParams} from "react-router-dom";
import {ArrowRight,CheckCircle2,ChevronDown,Clock3,Mail,MapPin,Phone,Play,Search,Send,Star,Users,Video,WalletCards} from "lucide-react";
import ReactPlayer from "react-player";
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import interactionPlugin from "@fullcalendar/interaction";
import {AppShell,Card,LineChart,PageTitle,Stat,Table,Logo,cn} from "./components";
import {useAuth} from "./auth";
import {courses as fallbackCourses,instructors,sampleRows} from "./data";
import {getData} from "./api";

export function PublicLayout({children}:{children:ReactNode}){return <div className="min-h-screen bg-[#F8F7FC]"><header className="h-16 bg-white border-b border-slate-100 flex items-center px-8 justify-between sticky top-0 z-30"><Logo/><nav className="hidden md:flex gap-7 text-xs text-slate-500"><Link to="/about">About</Link><Link to="/courses">Courses</Link><Link to="/instructors">Instructors</Link><Link to="/faq">FAQ</Link><Link to="/contact">Contact</Link></nav><div className="flex gap-2"><Link to="/login" className="px-4 py-2 text-xs font-semibold text-slate-600">Login</Link><Link to="/register" className="px-4 py-2 bg-brand text-white rounded-xl text-xs font-semibold">Get started</Link></div></header>{children}<footer className="bg-white border-t border-slate-100 p-8 mt-12 text-center text-xs text-slate-400">© 2026 Heartify. Learn with confidence.</footer></div>}

export function Home(){return <PublicLayout><section className="max-w-6xl mx-auto px-6 py-16 grid md:grid-cols-2 gap-10 items-center"><div><span className="inline-flex px-3 py-1 rounded-full bg-[#EDE8FF] text-brand text-xs font-semibold">Online Learning Platform</span><h1 className="text-5xl md:text-6xl font-bold leading-[1.05] mt-5">Learn with <span className="text-brand">confidence.</span></h1><p className="text-slate-500 mt-5 max-w-lg leading-7">Build practical skills with expert-led courses, projects, assessments and certificates — all in one place.</p><div className="flex gap-3 mt-7"><Link to="/courses" className="bg-brand text-white rounded-xl px-5 py-3 text-sm font-semibold">Explore courses <ArrowRight className="inline ml-2" size={15}/></Link><Link to="/register" className="bg-white border border-slate-200 rounded-xl px-5 py-3 text-sm font-semibold">Join Heartify</Link></div><div className="flex gap-7 mt-9 text-xs text-slate-500"><span><b className="text-slate-900 text-lg">24k+</b><br/>Learners</span><span><b className="text-slate-900 text-lg">120+</b><br/>Courses</span><span><b className="text-slate-900 text-lg">4.9</b><br/>Average rating</span></div></div><div className="relative"><div className="bg-[#EAE4FF] rounded-[2rem] p-8 h-[390px] flex items-end"><div className="bg-white rounded-2xl p-5 w-full shadow-xl"><div className="flex justify-between"><span className="font-semibold">Your learning journey</span><span className="text-brand text-xs">68%</span></div><div className="h-2 bg-slate-100 rounded-full mt-4"><div className="h-2 bg-brand rounded-full w-[68%]"/></div><div className="grid grid-cols-3 gap-3 mt-6">{["Courses","Lessons","Certificates"].map((x,i)=><div key={x} className="p-3 rounded-xl bg-[#F8F7FC]"><p className="text-[10px] text-slate-400">{x}</p><p className="font-bold mt-1">{[4,38,2][i]}</p></div>)}</div></div></div></div></section><section className="max-w-6xl mx-auto px-6 py-8"><PageTitle title="Featured courses" desc="Learn skills that move your career forward."/><div className="grid md:grid-cols-4 gap-4">{fallbackCourses.map(c=><CourseCard key={c.id} course={c}/>)}</div></section></PublicLayout>}

export function About(){return <PublicLayout><section className="max-w-6xl mx-auto px-6 py-16"><div className="max-w-2xl"><span className="text-brand text-xs font-semibold">About Heartify</span><h1 className="text-4xl font-bold mt-3">Learning that feels clear, practical and human.</h1><p className="text-slate-500 mt-5 leading-7">Heartify brings courses, instructors, projects, assessments and learning progress together in a simple experience.</p></div><div className="grid md:grid-cols-4 gap-4 mt-12">{["10k+","120+","4.9/5","95%"].map((x,i)=><Card key={i} className="p-5"><p className="text-2xl font-bold">{x}</p><p className="text-xs text-slate-400 mt-2">{["Active learners","Courses","Learner rating","Completion"][i]}</p></Card>)}</div></section></PublicLayout>}

function CourseCard({course}:any){return <Card className="overflow-hidden"><img src={course.thumbnail} className="w-full h-36 object-cover"/><div className="p-4"><p className="text-[10px] text-brand font-semibold">{course.category_name}</p><h3 className="font-semibold text-sm mt-1">{course.title}</h3><p className="text-[11px] text-slate-400 mt-2">{course.level} · {course.duration}</p><div className="flex justify-between items-center mt-4"><span className="font-bold">${course.price}</span><Link to={`/courses/${course.slug}`} className="text-brand text-xs font-semibold">View course</Link></div></div></Card>}

export function Courses(){const [items,setItems]=useState<any[]>(fallbackCourses);useEffect(()=>{getData("/public/courses/",fallbackCourses).then(setItems)},[]);return <PublicLayout><section className="max-w-6xl mx-auto px-6 py-12"><PageTitle title="Explore Courses" desc="Choose a path and start learning."/><div className="flex gap-3 mb-6"><div className="bg-white border border-slate-100 rounded-xl px-3 py-2 flex items-center flex-1 max-w-md"><Search size={15} className="text-slate-400"/><input placeholder="Search courses..." className="outline-none ml-2 text-xs w-full"/></div>{["All","Development","Design","Business"].map(x=><button key={x} className="px-3 py-2 rounded-xl bg-white border border-slate-100 text-xs">{x}</button>)}</div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{items.map(c=><CourseCard key={c.id} course={c}/>)}</div></section></PublicLayout>}

export function CourseDetails(){const {slug}=useParams();const course=fallbackCourses.find(c=>c.slug===slug)||fallbackCourses[0];return <PublicLayout><section className="max-w-6xl mx-auto px-6 py-12"><div className="grid lg:grid-cols-[1.4fr_.6fr] gap-8"><div><p className="text-brand text-xs font-semibold">{course.category_name}</p><h1 className="text-4xl font-bold mt-3">{course.title}</h1><p className="text-slate-500 mt-4 leading-7">{course.description}</p><div className="flex gap-6 text-xs text-slate-500 mt-5"><span><Clock3 size={14} className="inline mr-1"/> {course.duration}</span><span><Users size={14} className="inline mr-1"/> 2,431 learners</span><span><Star size={14} className="inline mr-1 text-brand"/> 4.9</span></div><Card className="p-5 mt-8"><h2 className="font-semibold">Course curriculum</h2>{["Introduction","Core concepts","Practical workshop","Build the project","Final review"].map((x,i)=><div key={x} className="flex items-center gap-3 py-4 border-b last:border-0"><span className="w-7 h-7 rounded-lg bg-[#F0ECFF] text-brand grid place-items-center text-xs">{i+1}</span><span className="text-sm">{x}</span><span className="ml-auto text-xs text-slate-400">15 min</span></div>)}</Card></div><Card className="p-4 h-fit"><img src={course.thumbnail} className="w-full h-44 object-cover rounded-xl"/><p className="text-3xl font-bold mt-5">${course.price}</p><Link to="/register" className="block text-center bg-brand text-white rounded-xl py-3 mt-4 text-sm font-semibold">Enroll now</Link><div className="space-y-3 text-xs text-slate-500 mt-5"><p>✓ Lifetime access</p><p>✓ Certificate of completion</p><p>✓ Project-based learning</p><p>✓ Instructor support</p></div></Card></div></section></PublicLayout>}

export function Instructors(){return <PublicLayout><section className="max-w-6xl mx-auto px-6 py-12"><PageTitle title="Meet Our Instructors" desc="Learn from experienced professionals."/><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{instructors.map(i=><Card key={i.name} className="p-5 text-center"><img src={i.avatar} className="w-20 h-20 rounded-full mx-auto"/><h3 className="font-semibold mt-4">{i.name}</h3><p className="text-xs text-slate-400 mt-1">{i.role}</p><div className="flex justify-center gap-4 text-xs mt-4"><span>{i.students} students</span><span>★ {i.rating}</span></div></Card>)}</div></section></PublicLayout>}

export function FAQ(){const qs=["How does Heartify work?","Do courses include certificates?","Can I learn at my own pace?","How can I contact an instructor?","Can I access courses on mobile?"];const [open,setOpen]=useState(0);return <PublicLayout><section className="max-w-3xl mx-auto px-6 py-16"><p className="text-brand text-xs font-semibold">FAQ</p><h1 className="text-4xl font-bold mt-2">Frequently Asked Questions</h1><div className="mt-8 space-y-3">{qs.map((q,i)=><Card key={q} className="p-5 cursor-pointer" onClick={()=>setOpen(open===i?-1:i)}><div className="flex justify-between font-semibold text-sm"><span>{q}</span><ChevronDown size={17}/></div>{open===i&&<p className="text-xs text-slate-500 mt-3 leading-6">Heartify combines structured courses, lessons, assessments, progress tracking and instructor support. You can learn on your own schedule and track completion from your dashboard.</p>}</Card>)}</div></section></PublicLayout>}

export function Contact(){return <PublicLayout><section className="max-w-6xl mx-auto px-6 py-12 grid md:grid-cols-2 gap-8"><div><p className="text-brand text-xs font-semibold">Contact</p><h1 className="text-4xl font-bold mt-2">Get in touch.</h1><p className="text-slate-500 mt-4">Have a question? Our support team is ready to help.</p><div className="space-y-5 mt-8 text-sm text-slate-500"><p><Mail className="inline mr-3 text-brand" size={18}/>support@heartify.com</p><p><Phone className="inline mr-3 text-brand" size={18}/>+91 98765 43210</p><p><MapPin className="inline mr-3 text-brand" size={18}/>New Delhi, India</p></div></div><Card className="p-6 space-y-4"><input className="field" placeholder="Your name"/><input className="field" placeholder="Email address"/><textarea className="field h-32" placeholder="How can we help?"/><button className="w-full bg-brand text-white rounded-xl py-3 text-sm font-semibold">Send message</button></Card></section></PublicLayout>}

function AuthPage({mode}:{mode:"login"|"register"|"forgot"|"reset"|"verify"}){
  const {login,register}=useAuth();
  const nav=useNavigate();
  const [email,setEmail]=useState("");
  const [password,setPassword]=useState("");
  const [name,setName]=useState("");
  const [error,setError]=useState("");
  const [busy,setBusy]=useState(false);
  const titles={login:"Login",register:"Register",forgot:"Forgot Password",reset:"Reset Password",verify:"Verification"};

  async function submit(){
    setError("");
    if(mode==="login"){
      if(!email.trim()||!password){setError("Enter your email and password.");return;}
      setBusy(true);
      const loggedUser=await login(email.trim(),password);
      setBusy(false);
      if(!loggedUser){setError("Invalid email/username or password, or the backend is unavailable.");return;}
      nav(`/${loggedUser.role}/dashboard`,{replace:true});
    }else if(mode==="register"){
      if(!name.trim()||!email.trim()||password.length<6){setError("Enter your name, a valid email and a password with at least 6 characters.");return;}
      setBusy(true);
      const ok=await register({email:email.trim(),password,first_name:name.trim()});
      setBusy(false);
      if(!ok){setError("Registration failed. The email may already be registered or the backend may be unavailable.");return;}
      nav("/login",{replace:true});
    }else{
      nav("/login",{replace:true});
    }
  }

  return <div className="min-h-screen bg-[#EAE4FF] flex"><div className="hidden lg:flex flex-1 items-center justify-center p-16"><div className="max-w-lg"><Logo/><h1 className="text-5xl font-bold mt-12">Learn with<br/><span className="text-brand">confidence.</span></h1><p className="text-slate-500 mt-5 leading-7">Everything you need to learn, practice and grow.</p></div></div><div className="w-full lg:w-[46%] bg-[#F8F7FC] flex items-center justify-center p-6"><Card className="w-full max-w-md p-8"><Logo/><h2 className="text-2xl font-bold mt-10">{titles[mode]}</h2><p className="text-xs text-slate-400 mt-2">{mode==="login"?"Welcome back. Continue your learning journey.":"Enter your details to continue."}</p>{mode==="register"&&<input className="field mt-7" placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/>}<input type="email" className="field mt-4" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/>{! ["forgot","verify"].includes(mode)&&<input type="password" className="field mt-4" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>} {error&&<p className="mt-3 text-xs text-red-600">{error}</p>}<button disabled={busy} onClick={submit} className="w-full bg-brand disabled:opacity-60 text-white rounded-xl py-3 mt-5 text-sm font-semibold">{busy?"Please wait…":titles[mode]}</button>{mode==="login"&&<div className="flex justify-between mt-4 text-xs"><Link to="/forgot-password" className="text-brand">Forgot password?</Link><Link to="/register" className="text-slate-500">Create account</Link></div>}{mode==="register"&&<p className="text-xs text-center mt-4">Already have an account? <Link className="text-brand" to="/login">Login</Link></p>}</Card></div></div>
}
export const Login=()=> <AuthPage mode="login"/>; export const Register=()=> <AuthPage mode="register"/>; export const ForgotPassword=()=> <AuthPage mode="forgot"/>; export const ResetPassword=()=> <AuthPage mode="reset"/>; export const Verification=()=> <AuthPage mode="verify"/>;

const titles:any={student:{dashboard:"Dashboard","my-courses":"My Courses","course-player":"Course Player",lessons:"Lessons",assignments:"Assignments",quizzes:"Quizzes",exams:"Exams",calendar:"Calendar",progress:"Progress",certificates:"Certificates",messages:"Messages",notifications:"Notifications",profile:"Profile",settings:"Settings"},instructor:{dashboard:"Dashboard",courses:"Courses","create-course":"Create Course",lessons:"Lessons",assignments:"Assignments",quizzes:"Quizzes",exams:"Exams",students:"Students",gradebook:"Gradebook",attendance:"Attendance","live-classes":"Live Classes",messages:"Messages",profile:"Profile",settings:"Settings"},admin:{dashboard:"Dashboard",users:"Users",instructors:"Instructors",courses:"Courses",categories:"Categories",enrollments:"Enrollments",assignments:"Assignments",quizzes:"Quizzes",exams:"Exams",certificates:"Certificates",reviews:"Reviews",reports:"Reports",notifications:"Notifications",support:"Support",profile:"Profile",settings:"Settings"}};

const rowsFor=(key:string)=> (sampleRows as any)[key] || [["Item 01","Sample information","Active"],["Item 02","Sample information","Pending"],["Item 03","Sample information","Active"],["Item 04","Sample information","Active"]];
const headerFor=(key:string)=>({users:["User","Email","Role","Status"],instructors:["Instructor","Specialty","Students","Rating"],courses:["Course","Instructor","Students","Price"],categories:["Category","Courses","Students","Status"],enrollments:["Student","Course","Progress","Enrolled"],assignments:["Assignment","Course","Due date","Status"],quizzes:["Quiz","Course","Questions","Status"],exams:["Exam","Course","Marks","Date"],certificates:["Certificate","Course","Student","Issued"],reviews:["Student","Course","Rating","Comment"],notifications:["Title","Message","Date","Status"],support:["Ticket","User","Subject","Status"]} as any)[key]||["Name","Details","Status"];

export function Dashboard({role}:{role:"student"|"instructor"|"admin"}){const config=role==="student"?{title:"Dashboard",stats:[["Courses","04","2 active"],["Lessons","38","6 this week"],["Progress","68%","+12%"],["Certificates","02","Completed"]]}:role==="instructor"?{title:"Dashboard",stats:[["Courses","12","+2 this month"],["Students","2,431","+8.2%"],["Completion","86%","+4.1%"],["Rating","4.9","Excellent"]]}:{title:"Dashboard",stats:[["Users","12,842","+8.2%"],["Courses","120","+6 this month"],["Revenue","$48.2k","+12.4%"],["Completion","81%","+4.6%"]]};return <AppShell role={role} title={config.title} subtitle="Overview of your learning platform"><div className="grid md:grid-cols-4 gap-4">{config.stats.map(([a,b,c],i)=><Stat key={a} label={a} value={b} change={c}/>)}</div><div className="grid lg:grid-cols-[1fr_280px] gap-5 mt-5"><Card className="p-5"><div className="flex justify-between items-center"><div><h3 className="font-semibold text-sm">Learning activity</h3><p className="text-[11px] text-slate-400">Weekly overview</p></div><select className="text-xs border border-slate-200 rounded-lg px-2 py-1"><option>This week</option><option>This month</option></select></div><LineChart/></Card><Card className="p-5"><h3 className="font-semibold text-sm">Upcoming</h3><div className="space-y-4 mt-5">{["React Assignment","Python Quiz","Live class"].map((x,i)=><div key={x} className="flex gap-3"><span className="w-2 h-2 mt-1.5 rounded-full bg-brand"/><div><p className="text-xs font-medium">{x}</p><p className="text-[10px] text-slate-400">{["Today, 6:00 PM","Tomorrow, 10:00 AM","Fri, 5:00 PM"][i]}</p></div></div>)}</div></Card></div><Card className="p-5 mt-5"><h3 className="font-semibold text-sm">Recent activity</h3><Table headers={["Activity","Course","Date","Status"]} rows={rowsFor("enrollments")}/></Card></AppShell>}

export function GenericPage({role,keyName}:{role:"student"|"instructor"|"admin";keyName:string}){const title=titles[role][keyName]||keyName;const special=keyName==="calendar";const isSettings=keyName==="settings";if(special)return <CalendarPage role={role}/>;if(keyName==="course-player")return <CoursePlayer/>;if(keyName==="create-course")return <CreateCourse/>;if(keyName==="messages")return <Messages role={role}/>;if(keyName==="profile")return <Profile role={role}/>;if(isSettings)return <SettingsPage role={role}/>;const keyMap:any={"my-courses":"courses","lessons":"courses","students":"users","gradebook":"enrollments","attendance":"enrollments","live-classes":"assignments","reports":"enrollments"};const dataKey=keyMap[keyName]||keyName;return <AppShell role={role} title={title} subtitle={`Manage ${title.toLowerCase()} in Heartify`}><PageTitle title={title} desc={`Keep your ${title.toLowerCase()} organized and up to date.`} button={["courses","students","assignments","quizzes","exams","categories"].includes(dataKey)?`Add ${title.slice(0,-1)}`:undefined}/><div className="grid md:grid-cols-3 gap-4 mb-5"><Stat label="Total" value={dataKey==="users"?"12,842":dataKey==="courses"?"120":dataKey==="enrollments"?"8,421":"24"} /><Stat label="Active" value={dataKey==="courses"?"96":"86%"} /><Stat label="This month" value="+12%" /></div><Table headers={headerFor(dataKey)} rows={rowsFor(dataKey)}/></AppShell>}

function CalendarPage({role}:any){return <AppShell role={role} title="Calendar" subtitle="Your schedule"><div className="grid lg:grid-cols-[1fr_280px] gap-5"><Card className="p-5"><FullCalendar plugins={[dayGridPlugin,interactionPlugin]} initialView="dayGridMonth" height="auto" events={[{title:"React Assignment",date:"2026-09-20"},{title:"Python Quiz",date:"2026-09-22"},{title:"Live Class",date:"2026-09-25"}]}/></Card><Card className="p-5"><h3 className="font-semibold text-sm">Today</h3>{["10:00 AM Python lesson","2:00 PM Assignment","6:00 PM Live class"].map(x=><div key={x} className="p-3 rounded-xl bg-[#F8F7FC] mt-3 text-xs">{x}</div>)}</Card></div></AppShell>}

function CoursePlayer(){return <AppShell role="student" title="Course Player" subtitle="Full Stack Web Development"><div className="grid lg:grid-cols-[1fr_320px] gap-5"><Card className="overflow-hidden"><div className="aspect-video bg-[#201E35]"><ReactPlayer src="https://www.youtube.com/watch?v=dQw4w9WgXcQ" width="100%" height="100%" controls light={false}/></div><div className="p-5"><p className="text-xs text-brand">Lesson 3 of 12</p><h2 className="font-bold text-lg mt-2">Build your first React component</h2><p className="text-xs text-slate-400 mt-2">Learn component structure, props and reusable UI patterns.</p></div></Card><Card className="p-4"><h3 className="font-semibold text-sm">Course content</h3>{["Introduction","HTML & CSS","React components","State & props","Project"].map((x,i)=><div key={x} className={cn("flex gap-3 p-3 rounded-xl mt-2 text-xs",i===2?"bg-[#F0ECFF]":"")}><span className="w-6 h-6 rounded-full bg-slate-100 grid place-items-center">{i+1}</span>{x}<span className="ml-auto text-slate-400">15m</span></div>)}</Card></div></AppShell>}

function CreateCourse(){return <AppShell role="instructor" title="Create Course"><Card className="p-6 max-w-4xl"><div className="grid md:grid-cols-2 gap-4"><input className="field" placeholder="Course title"/><input className="field" placeholder="Price"/><select className="field"><option>Development</option><option>Design</option></select><select className="field"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></div><textarea className="field mt-4 h-32" placeholder="Course description"/><div className="border-2 border-dashed border-slate-200 rounded-2xl p-10 text-center text-xs text-slate-400 mt-4">Upload course thumbnail</div><button className="bg-brand text-white rounded-xl px-5 py-3 text-xs font-semibold mt-5">Publish Course</button></Card></AppShell>}

function Messages({role}:any){return <AppShell role={role} title="Messages"><div className="grid lg:grid-cols-[280px_1fr] gap-5"><Card className="p-3">{["Michael Young","Sarah Wilson","Support Team"].map((x,i)=><div className={cn("p-4 rounded-xl text-xs",i===0?"bg-[#F0ECFF]":"")} key={x}><b>{x}</b><p className="text-slate-400 mt-1">Latest conversation</p></div>)}</Card><Card className="p-5 min-h-[450px] flex flex-col"><div className="flex-1"><h3 className="font-semibold text-sm">Conversation</h3><div className="bg-[#F8F7FC] rounded-2xl p-4 mt-6 max-w-md text-xs">Hello! How can I help you with your course?</div><div className="bg-brand text-white rounded-2xl p-4 mt-3 max-w-md ml-auto text-xs">I have a question about the assignment.</div></div><div className="flex gap-2"><input className="field" placeholder="Type a message..."/><button className="bg-brand text-white rounded-xl px-4"><Send size={17}/></button></div></Card></div></AppShell>}

function Profile({role}:{role:"student"|"instructor"|"admin"}){const {user}=useAuth();const roleLabel=role.charAt(0).toUpperCase()+role.slice(1);return <AppShell role={role} title="Profile"><Card className="p-6 max-w-3xl"><div className="flex items-center gap-4"><img src="https://i.pravatar.cc/100?img=12" className="w-20 h-20 rounded-full"/><div><h2 className="font-bold text-lg">{user?.first_name||"Alex"} {user?.last_name||"Morgan"}</h2><p className="text-xs text-slate-400">{roleLabel} · {user?.email||"alex@example.com"}</p></div></div><div className="grid md:grid-cols-2 gap-4 mt-8"><input className="field" value={user?.first_name||"Alex"} readOnly/><input className="field" value={user?.last_name||"Morgan"} readOnly/><input className="field" value={user?.email||"alex@example.com"} readOnly/><input className="field" value="+91 98765 43210" readOnly/></div><button className="bg-brand text-white rounded-xl px-5 py-3 text-xs font-semibold mt-5">Save changes</button></Card></AppShell>}

function SettingsPage({role}:any){return <AppShell role={role} title="Settings"><Card className="max-w-3xl divide-y divide-slate-100">{["Email notifications","Course reminders","Assignment alerts","Marketing updates"].map((x,i)=><div key={x} className="p-5 flex justify-between"><div><p className="text-sm font-medium">{x}</p><p className="text-xs text-slate-400 mt-1">Manage your Heartify notification preference.</p></div><div className={cn("w-10 h-6 rounded-full p-1",i===3?"bg-slate-200":"bg-brand")}><div className={cn("w-4 h-4 rounded-full bg-white",i===3?"":"ml-4")}/></div></div>)}</Card></AppShell>}
